version: "3.8"

services:
  app:
    image: python:3.10
    container_name: private_doc_bot
    working_dir: /app
    volumes:
      - ./PrivateDocBot:/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    
    command: >
      bash -c "pip install --upgrade pip && 
      pip install -r requirements.txt && 
      chainlit run main.py -w --host 0.0.0.0"
    ports:
      - "8000:8000"  # Chainlit runs on port 8000
    networks:
      - private-doc-bot-network

networks:
  private-doc-bot-network:
    name: private-doc-bot-network
    external: true
